### ISSUE TITLE
No ALB created

### ISSUE THREAD

**Issue by floknip** [aws-samples/cdk-eks-fargate#3]
cdk deploy went through successfully but seems like there is not ALB created. 

```bash
$ kubectl get ingress -A     
NAMESPACE   NAME          CLASS    HOSTS   ADDRESS   PORTS   AGE
nginx       api-ingress   <none>   *                 80      20m
```

Did not reference an existing VPC. Pods seem to be ok and created. Any idea where to look at? Many thanks in advance

**Comment by floknip** [comment]
Update:

Actually found the issue mentioned above. It was a permission error that I uncovered on `k logs -n kube-system <nameOfApplicationLoadBalancerController>`

Changed this
https://github.com/aws-samples/cdk-eks-fargate/blob/aa3f94fd22652210b80f3dd25fefc51af653321d/lib/aws-loadbalancer-controller.ts#L57-L80

to `ec2:*` for now and that error went off. This one currently makes ALB Provioning work for 'internal' facing loadbalancer.

**Comment by JasperW01** [comment]
Thx a lot, @floknip . Do you mind to share which exact EC2 permission it complains about? I will try to replicate on my side as well. It's possible that the latest version of ALB might require new IAM permission.

**Comment by floknip** [comment]
> Thx a lot, @floknip . Do you mind to share which exact EC2 permission it complains about? I will try to replicate on my side as well. It's possible that the latest version of ALB might require new IAM permission.

You should see it on `kubectl log <deploymentOfALBController>`
Complain is this on:
```
couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation
```

Created a [PR](https://github.com/aws-samples/cdk-eks-fargate/pull/5) that adds the missing permission. Create the ALB for me now.  Found the solution here initially: https://githubmemory.com/repo/kubernetes-sigs/aws-load-balancer-controller/issues/2018

**Comment by JasperW01** [comment]
Thank you very much for your great help, @floknip . yeah, as you pointed out, it looks like the newer version requires another new IAM permission.  

I have merged your PR and again thank you for you reporting the issue and providing the fix. 

Cheers. 

Jasper

**Comment by JasperW01** [comment]
Issue addressed by https://github.com/aws-samples/cdk-eks-fargate/pull/5
